spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
   
    url: jdbc:mysql://localhost:3306/narvee
    username: root
    password: manu
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
